[package]
name = "hackcmu"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
bevy_egui = "0.36.0"
egui_extras = {version = "0.32.3", features = ["syntect"]}
syntect = "5.2.0"
